### ISSUE TITLE
App example is currently broken won't start

### ISSUE THREAD

**Issue by eriknyk** [bpmn-io/bpmn-js-example-react-properties-panel#5]
### App example s broken, won't start

```
npm run start
```

Output
```
> bpmn-js-example-react-properties-panel@0.0.0 start
> webpack-dev-server --open

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
node:internal/crypto/hash:68
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/erik/WFSandbox/bpmn-js-example-react-properties-panel/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/Users/erik/WFSandbox/bpmn-js-example-react-properties-panel/node_modules/webpack/lib/NormalModule.js:401:16)
    at handleParseError (/Users/erik/WFSandbox/bpmn-js-example-react-properties-panel/node_modules/webpack/lib/NormalModule.js:449:10)
    at /Users/erik/WFSandbox/bpmn-js-example-react-properties-panel/node_modules/webpack/lib/NormalModule.js:481:5
    at /Users/erik/WFSandbox/bpmn-js-example-react-properties-panel/node_modules/webpack/lib/NormalModule.js:342:12
    at /Users/erik/WFSandbox/bpmn-js-example-react-properties-panel/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/erik/WFSandbox/bpmn-js-example-react-properties-panel/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/erik/WFSandbox/bpmn-js-example-react-properties-panel/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/erik/WFSandbox/bpmn-js-example-react-properties-panel/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at /Users/erik/WFSandbox/bpmn-js-example-react-properties-panel/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9
    at /Users/erik/WFSandbox/bpmn-js-example-react-properties-panel/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

### Steps to Reproduce

1. do this
2. do that
3. now this happens

### Expected Behavior
Just try start project
```
npm run start
```

### Environment
- Node.js v20.10.0
- OS: Darwin 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64 x86_64

**Comment by eriknyk** [comment]
I made an updated app with latest version of react bpmn-js and functional component

https://github.com/eriknyk/bpmn-js-react-properties-panel-example

**Comment by eriknyk** [comment]
Just wanted to contribute with the updated version  https://github.com/bpmn-io/bpmn-js-example-react-properties-panel/pull/6
